### ISSUE TITLE
Add screen sharing example

### ISSUE THREAD

**Issue by stefanalund** [Ericsson/c3-web-examples#12]
Example should show how screen can be shared. Display on the same page similarly to how https://mozilla.github.io/webrtc-landing/gum_test.html works.

**Comment by stefanalund** [comment]
Assigning @Guaschman to this one.

**Comment by stefanalund** [comment]
I noticed Firefox has whitelisted `*.github.io` which should come in handy.

**Comment by negzi** [comment]
Yes that is useful, we don't need an extension then. But it is good to have the example on how to do it here anyways I think. Also if you check whitelisted domains in FF you can see that *.ericsson.net is whitelisted as well,  meaning that we do not need to whitelist any of our domains since all of them are subdomains of ".ericsson.net". What do you think Stefan?

**Comment by stefanalund** [comment]
I'd say we can close this one now as we have https://github.com/Ericsson/c3-web-examples/tree/gh-pages/screen-sharing Thanks @negzi
